name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test_db;'
          mysql -uroot -h127.0.0.1 -proot test_db < ./sql-data/dummy.sql
          mysql -uroot -h127.0.0.1 -proot -e 'SELECT * FROM test_db.persons;'

      - name: Install Packages
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Test types
        run: yarn test:types

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true
          MYSQL_DATABASE: 'test_db'
          MYSQL_PASSWORD: 'root'
          MYSQL_USER: 'root'
          MYSQL_HOST: '127.0.0.1'

